# Generated by Django 4.2.5 on 2023-10-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementaciones',
            name='id_implementacion',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
