# Generated by Django 4.2.5 on 2023-10-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0003_alter_cliente_industria_alter_cliente_site_and_more'),
        ('api_cmdb', '0003_alter_implementaciones_id_implementacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementaciones',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientdata.cliente'),
        ),
        migrations.AlterField(
            model_name='implementaciones',
            name='status_interno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_cmdb.status_implementaciones'),
        ),
    ]
