# Generated by Django 4.2.5 on 2023-10-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_cmdb', '0004_alter_implementaciones_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='implementaciones',
            options={'verbose_name': 'Implementaciones', 'verbose_name_plural': 'Implementaciones'},
        ),
        migrations.AlterModelOptions(
            name='status_implementaciones',
            options={'verbose_name': 'Estado de implementaciones', 'verbose_name_plural': 'Estado de implementaciones'},
        ),
    ]
