# Generated by Django 4.2.5 on 2023-10-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConduceEntrada',
            fields=[
                ('id_conduce_entrada', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('statusc', models.CharField(default='Entrada', max_length=10)),
                ('direccion', models.CharField(default='Av. Lope de Vega #19, Edif. PIISA, Bloque A, Suite 401 Naco, Santo Domingo, R.D', max_length=150)),
                ('Telefono', models.CharField(default='809-566-3495', max_length=150)),
                ('rnc1', models.CharField(default='RNC.1-30-26091-5 [S.A]', max_length=50)),
                ('rnc2', models.CharField(default='RNC.1-30-48300-2 [INC]', max_length=50)),
                ('nombre_empresa', models.CharField(default='NAP Del Caribe', max_length=50)),
                ('fecha_entrada', models.DateField()),
                ('notas', models.CharField(max_length=255)),
                ('nombre_representante_cliente', models.CharField(max_length=100)),
                ('documento_identidad_cliente', models.CharField(max_length=50)),
                ('nombre_empleado_napc', models.CharField(max_length=100)),
                ('empresa_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ConduceSalida',
            fields=[
                ('id_conduce_salida', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('statusc', models.CharField(default='Salida', max_length=10)),
                ('direccion', models.CharField(default='Av. Lope de Vega #19, Edif. PIISA, Bloque A, Suite 401 Naco, Santo Domingo, R.D', max_length=150)),
                ('Telefono', models.CharField(default='809-566-3495', max_length=150)),
                ('rnc1', models.CharField(default='RNC.1-30-26091-5 [S.A]', max_length=50)),
                ('rnc2', models.CharField(default='RNC.1-30-48300-2 [INC]', max_length=50)),
                ('nombre_empresa', models.CharField(default='NAP Del Caribe', max_length=50)),
                ('fecha_salida', models.DateField()),
                ('notas', models.CharField(max_length=255)),
                ('nombre_representante_cliente', models.CharField(max_length=100)),
                ('documento_identidad_cliente', models.CharField(max_length=50)),
                ('nombre_empleado_napc', models.CharField(max_length=100)),
                ('empresa_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Salida',
            fields=[
                ('id_equipo_salida', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('nombre_equipo', models.CharField(max_length=30)),
                ('modelo_equipo', models.CharField(max_length=30)),
                ('descripcion_equipo', models.CharField(max_length=100)),
                ('conduce_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conduces.conducesalida')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('nombre_equipo', models.CharField(max_length=30)),
                ('modelo_equipo', models.CharField(max_length=30)),
                ('descripcion_equipo', models.CharField(max_length=100)),
                ('conduce_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conduces.conduceentrada')),
            ],
        ),
    ]
