# Generated by Django 4.2.5 on 2023-10-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0002_alter_contacto_telefono'),
        ('conduces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=30)),
                ('modelo_equipo', models.CharField(max_length=30)),
                ('descripcion_equipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario_Salida',
            fields=[
                ('id_equipo_salida', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=30)),
                ('modelo_equipo', models.CharField(max_length=30)),
                ('descripcion_equipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='AprobacionAduanal',
        ),
        migrations.RemoveField(
            model_name='inventariof',
            name='conduce_entrada',
        ),
        migrations.RemoveField(
            model_name='inventariof',
            name='conduce_salida',
        ),
        migrations.RemoveField(
            model_name='inventariofirmado',
            name='conduce_entrada',
        ),
        migrations.RenameField(
            model_name='conducesalida',
            old_name='id_conduce_entrada',
            new_name='id_conduce_salida',
        ),
        migrations.RemoveField(
            model_name='conduceentrada',
            name='inventario_sf',
        ),
        migrations.RemoveField(
            model_name='conducesalida',
            name='inventario_f',
        ),
        migrations.AlterField(
            model_name='conduceentrada',
            name='empresa_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.cliente'),
        ),
        migrations.AlterField(
            model_name='conducesalida',
            name='empresa_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.cliente'),
        ),
        migrations.DeleteModel(
            name='conduceEntradaRealizado',
        ),
        migrations.DeleteModel(
            name='conduceSalidaRealizado',
        ),
        migrations.DeleteModel(
            name='inventarioF',
        ),
        migrations.DeleteModel(
            name='inventarioFirmado',
        ),
        migrations.DeleteModel(
            name='inventarioSinFirmar',
        ),
        migrations.AddField(
            model_name='inventario_salida',
            name='conduce_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conduces.conducesalida'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='conduce_entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conduces.conduceentrada'),
        ),
    ]
