# Generated by Django 4.2.5 on 2023-10-09 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id_servicios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('estado_status', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Ordenes_De_Servicio',
            fields=[
                ('id_ods', models.AutoField(primary_key=True, serialize=False)),
                ('nomeclatura_ods', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientdata.cliente')),
                ('servicio_contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicios')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.status')),
            ],
        ),
    ]
