# Generated by Django 4.2.5 on 2023-09-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='servicios',
            fields=[
                ('id_servicios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_sc', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientdata.cliente')),
                ('servicio_contratado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicios')),
            ],
        ),
    ]
