# Generated by Django 4.2.5 on 2023-10-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenes_de_servicio',
            options={'verbose_name': 'Orden de servicio', 'verbose_name_plural': 'Ordenes de servicios'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Estado (Servicios)', 'verbose_name_plural': 'Estados (Servicios)'},
        ),
    ]
