# Generated by Django 4.2.5 on 2023-10-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_servicio',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
