# Generated by Django 4.2.5 on 2023-09-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes_de_servicio',
            name='tiempo_servicios',
        ),
    ]
