# Generated by Django 4.2.5 on 2023-10-11 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0002_alter_contacto_telefono'),
        ('services', '0002_alter_ordenes_de_servicio_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes_de_servicio',
            name='clientes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.cliente'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_servicio',
            name='nomeclatura_ods',
            field=models.CharField(default='NOT DEFINED', max_length=100),
        ),
        migrations.AlterField(
            model_name='ordenes_de_servicio',
            name='servicio_contratado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.servicios'),
        ),
        migrations.AlterField(
            model_name='ordenes_de_servicio',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.status'),
        ),
    ]
