# Generated by Django 4.2.5 on 2023-10-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_ordenes_de_servicio_clientes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='status',
            name='descripcion',
        ),
    ]
