# Generated by Django 4.2.5 on 2023-09-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industria',
            fields=[
                ('id_industria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_industria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='nomeclatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeEntidad',
            fields=[
                ('id_entidad', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('publico', 'Público'), ('privado', 'Privado')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeOperacion',
            fields=[
                ('id_operacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('contingencia', 'Contingencia'), ('primario', 'Primario')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('nombre_contacto_directo', models.CharField(max_length=200)),
                ('correo_contacto_directo', models.EmailField(max_length=254, unique=True)),
                ('telefono_contacto_directo', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_inicio_contrato', models.DateTimeField()),
                ('direccion', models.CharField(max_length=200)),
                ('rnc', models.CharField(max_length=30)),
                ('status_cliente', models.CharField(choices=[('activo', 'Cliente Activo'), ('primario', 'Cliente Primario')], max_length=10)),
                ('industria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientdata.industria')),
                ('tipo_entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientdata.tipodeentidad')),
                ('tipo_operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientdata.tipodeoperacion')),
            ],
        ),
    ]
