# Generated by Django 4.2.5 on 2023-10-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('nomeclatura', models.CharField(default='', max_length=200)),
                ('nombre_empresa', models.CharField(max_length=200)),
                ('fecha_inicio_contrato', models.DateField()),
                ('direccion', models.CharField(max_length=200)),
                ('rnc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id_entidad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('entidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Industria',
            fields=[
                ('id_industria', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('nombre_industria', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id_localidad', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('localidad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id_operacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('operacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('nombre_contacto', models.CharField(max_length=100)),
                ('apellido_contacto', models.CharField(max_length=100)),
                ('identificacion', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='industria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.industria'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.localidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='status_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.status'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.entidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.operacion'),
        ),
    ]
