# Generated by Django 4.2.5 on 2023-09-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='site',
            field=models.CharField(choices=[('NAP West', 'NAP West'), ('NAP East', 'NAP East'), ('NAP Cloud', 'NAP Cloud'), ('N/A', 'N/A')], default='', max_length=20),
        ),
    ]
