# Generated by Django 4.2.5 on 2023-09-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0002_alter_cliente_fecha_inicio_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nomeclatura',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status_cliente',
            field=models.CharField(choices=[('activo', 'Cliente Activo'), ('inactivo', 'Cliente Inactivo')], max_length=10),
        ),
    ]
