# Generated by Django 4.2.5 on 2023-10-19 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0002_alter_cliente_industria_alter_cliente_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='industria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.industria'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.localidad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='status_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.status'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_entidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.entidad'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.operacion'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.cliente'),
        ),
    ]
