# Generated by Django 4.2.5 on 2023-10-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0002_alter_contacto_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidad',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='industria',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='localidad',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='status',
            name='descripcion',
        ),
    ]
