# Generated by Django 4.2.5 on 2023-10-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0003_alter_cliente_industria_alter_cliente_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto (Clientes)', 'verbose_name_plural': 'Contactos (Clientes)'},
        ),
        migrations.AlterModelOptions(
            name='entidad',
            options={'verbose_name': 'Entidad (Clientes)', 'verbose_name_plural': 'Entidades (Clientes)'},
        ),
        migrations.AlterModelOptions(
            name='industria',
            options={'verbose_name': 'Industria (Clientes)', 'verbose_name_plural': 'Industrias (Clientes)'},
        ),
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name': 'Localidad (Clientes)', 'verbose_name_plural': 'Localidades (Clientes)'},
        ),
        migrations.AlterModelOptions(
            name='operacion',
            options={'verbose_name': 'Operacion (Clientes)', 'verbose_name_plural': 'Operaciones (Clientes)'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Estado (Clientes)', 'verbose_name_plural': 'Estados (Clientes)'},
        ),
    ]
