# Generated by Django 4.2.5 on 2023-09-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0005_cliente_nombre_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombre_cliente',
        ),
    ]
