# Generated by Django 4.2.5 on 2023-09-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0006_remove_cliente_nombre_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='industria',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
