# Generated by Django 4.2.5 on 2023-09-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acl',
            fields=[
                ('id_acl', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('empresa', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('acceso', models.CharField(max_length=25)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'acl',
                'db_table_comment': 'Tabla con el ACL de los clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Acls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('empresa', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('acceso', models.CharField(max_length=25)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'acls',
                'db_table_comment': 'Tabla con el ACL de los clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AclTemporal',
            fields=[
                ('id_acl_temp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('apellido', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('empresa', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('email', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('autorizador', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('tecn_noc', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
            ],
            options={
                'db_table': 'acl_temporal',
                'db_table_comment': 'Tabla con el ACL de los clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('tipo_empresa', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('restringido', models.CharField(max_length=10)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'empresas',
                'db_table_comment': 'Tabla de los Clientes/Empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GridLocation',
            fields=[
                ('id_grid_location', models.AutoField(primary_key=True, serialize=False)),
                ('num_gabinete', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=75)),
                ('grid_location', models.CharField(max_length=75)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'grid_location',
                'db_table_comment': 'Tabla que guarda los Grid Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('personal', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=100)),
                ('grid_location', models.CharField(max_length=60)),
                ('firma', models.TextField()),
                ('hora_sal', models.CharField(max_length=25)),
                ('fecha_sal', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('empleado_ent', models.CharField(max_length=25)),
                ('fecha_ret', models.DateTimeField()),
                ('empleado_ret', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'historial',
                'db_table_comment': 'Formulario Registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialSoc',
            fields=[
                ('id_hist_soc', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=75)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('carnet', models.CharField(max_length=50)),
                ('personal_ent', models.CharField(max_length=50)),
                ('fecha_ent', models.CharField(max_length=30)),
                ('personal_rec', models.CharField(max_length=50)),
                ('fecha_rec', models.DateTimeField()),
            ],
            options={
                'db_table': 'historial_soc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistorialSocOld',
            fields=[
                ('id_hist_soc', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=75)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('carnet', models.CharField(max_length=50)),
                ('personal_ent', models.CharField(max_length=50)),
                ('fecha_ent', models.CharField(max_length=30)),
                ('personal_rec', models.CharField(max_length=50)),
                ('fecha_rec', models.DateTimeField()),
            ],
            options={
                'db_table': 'historial_soc_old',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LlavesActivas',
            fields=[
                ('id_activas', models.AutoField(primary_key=True, serialize=False)),
                ('grid_location', models.CharField(max_length=150)),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'llaves_activas',
                'db_table_comment': 'Tabla que contiene las llaves que estan activas actualmente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LlavesInternas',
            fields=[
                ('id_llaves_int', models.AutoField(primary_key=True, serialize=False)),
                ('num_gabinete', models.IntegerField()),
                ('cliente', models.CharField(max_length=75)),
                ('grid_location', models.CharField(max_length=75)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'llaves_internas',
                'db_table_comment': 'Tabla que guarda los Grid Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LlavesInternasa',
            fields=[
                ('id_llaves_int', models.AutoField(primary_key=True, serialize=False)),
                ('num_gabinete', models.IntegerField()),
                ('cliente', models.CharField(max_length=75)),
                ('grid_location', models.CharField(max_length=75)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'llaves_internasa',
                'db_table_comment': 'Tabla que guarda los Grid Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('proceso', models.CharField(db_collation='latin1_spanish_ci', max_length=150)),
                ('accion', models.CharField(db_collation='latin1_spanish_ci', max_length=250)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwAcl',
            fields=[
                ('id_acl', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('empresa', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('acceso', models.CharField(max_length=25)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'nw_acl',
                'db_table_comment': 'Tabla con el ACL de los clientes en NAP West',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwAclTemporal',
            fields=[
                ('id_acl_temp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('apellido', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('empresa', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('email', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('autorizador', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('tecn_noc', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
            ],
            options={
                'db_table': 'nw_acl_temporal',
                'db_table_comment': 'Tabla con el ACL de los clientes temporales en el NAP West',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwEmpresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('tipo_empresa', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('restringido', models.CharField(max_length=10)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'nw_empresas',
                'db_table_comment': 'Tabla de los Clientes/Empresas en el NAP West',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwGridLocation',
            fields=[
                ('id_grid_location', models.AutoField(primary_key=True, serialize=False)),
                ('num_gabinete', models.CharField(max_length=20)),
                ('cliente', models.CharField(max_length=75)),
                ('grid_location', models.CharField(max_length=75)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'nw_grid_location',
                'db_table_comment': 'Tabla que guarda los Grid Location en NAP West',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwHistorial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('personal', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=100)),
                ('grid_location', models.CharField(max_length=60)),
                ('firma', models.TextField()),
                ('hora_sal', models.CharField(max_length=25)),
                ('fecha_sal', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('empleado_ent', models.CharField(max_length=25)),
                ('fecha_ret', models.DateTimeField()),
                ('empleado_ret', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'nw_historial',
                'db_table_comment': 'Formulario Registro en NAP West',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwLlavesActivas',
            fields=[
                ('id_activas', models.AutoField(primary_key=True, serialize=False)),
                ('grid_location', models.CharField(max_length=150)),
                ('fecha_hora', models.DateTimeField()),
            ],
            options={
                'db_table': 'nw_llaves_activas',
                'db_table_comment': 'Tabla que contiene las llaves que estan activas actualmente el NAP West',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwLlavesInternas',
            fields=[
                ('id_llaves_int', models.AutoField(primary_key=True, serialize=False)),
                ('num_gabinete', models.IntegerField()),
                ('cliente', models.CharField(max_length=75)),
                ('grid_location', models.CharField(max_length=75)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'nw_llaves_internas',
                'db_table_comment': 'Tabla que guarda las llaves internas del NAP West',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwRestringidos',
            fields=[
                ('id_restringidos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('tipo_empresa', models.CharField(max_length=25)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'nw_restringidos',
                'db_table_comment': 'Clientes restringidos del NAP West',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwSalidaLlaves',
            fields=[
                ('id_salida_llaves', models.AutoField(primary_key=True, serialize=False)),
                ('personal', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('grid_location', models.CharField(max_length=125)),
                ('fecha', models.DateTimeField()),
                ('firma', models.TextField()),
                ('empleado_nap', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'nw_salida_llaves',
                'db_table_comment': 'Tabla con los registros de las llaves que se entregaron a los clientes en NAP West',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NwTecnicoNoc',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'nw_tecnico_noc',
                'db_table_comment': 'Tecnico NAP West',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistroSoc',
            fields=[
                ('id_reg_soc', models.AutoField(primary_key=True, serialize=False)),
                ('institucion', models.CharField(max_length=75)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('carnet', models.CharField(max_length=50)),
                ('personal_soc', models.CharField(max_length=50)),
                ('fecha_ent', models.DateTimeField()),
            ],
            options={
                'db_table': 'registro_soc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReporteSemanal',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('personal', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=100)),
                ('grid_location', models.CharField(max_length=150)),
                ('fecha', models.DateTimeField()),
                ('firma', models.TextField()),
                ('empleado_nap', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'reporte_semanal',
                'db_table_comment': 'Tabla con los registros de las llaves que se entregaron a los clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Restringidos',
            fields=[
                ('id_restringidos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('tipo_empresa', models.CharField(max_length=25)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'restringidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalidaLlaves',
            fields=[
                ('id_salida_llaves', models.AutoField(primary_key=True, serialize=False)),
                ('personal', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('grid_location', models.CharField(max_length=125)),
                ('fecha', models.DateTimeField()),
                ('firma', models.TextField()),
                ('empleado_nap', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'salida_llaves',
                'db_table_comment': 'Tabla con los registros de las llaves que se entregaron a los clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TecnicoNoc',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'tecnico_noc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateTimeField()),
                ('admin', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
