# Generated by Django 4.2.5 on 2023-10-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acl',
            options={'managed': False, 'verbose_name': 'ACL (Operaciones)', 'verbose_name_plural': 'ACLs (Operaciones)'},
        ),
        migrations.AlterModelOptions(
            name='acls',
            options={'managed': False, 'verbose_name': 'ACL', 'verbose_name_plural': 'ACLs'},
        ),
        migrations.AlterModelOptions(
            name='acltemporal',
            options={'managed': False, 'verbose_name': 'ACL Temporal (Operaciones)', 'verbose_name_plural': 'ACLs Temporales (Operaciones)'},
        ),
        migrations.AlterModelOptions(
            name='empresas',
            options={'managed': False, 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='gridlocation',
            options={'managed': False, 'verbose_name': 'Tarjeta de entrada', 'verbose_name_plural': 'Tarjetas de entrada'},
        ),
        migrations.AlterModelOptions(
            name='historial',
            options={'managed': False, 'verbose_name': 'Historial', 'verbose_name_plural': 'Historial'},
        ),
    ]
