# Generated by Django 4.2.5 on 2023-10-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=50)),
                ('tipo_empresa', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('restringido', models.CharField(max_length=10)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='permanente',
            fields=[
                ('id_acl', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('empresa', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('autorizador', models.CharField(db_collation='utf8mb3_spanish_ci', max_length=100)),
                ('acceso', models.CharField(max_length=25)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='temporal',
            fields=[
                ('id_acl_temp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('apellido', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('cedula', models.CharField(max_length=15)),
                ('empresa', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('email', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
                ('autorizador', models.CharField(max_length=100)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('tecn_noc', models.CharField(db_collation='latin1_swedish_ci', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restringidos',
            fields=[
                ('id_restringidos', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_empresa', models.CharField(max_length=25)),
                ('agregado_por', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField()),
                ('nombre_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='acl.empresas')),
            ],
        ),
    ]
