# Generated by Django 4.2.5 on 2023-10-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='permanente',
            options={'verbose_name': 'Empleado permanente', 'verbose_name_plural': 'Empleados permanentes'},
        ),
        migrations.AlterModelOptions(
            name='restringidos',
            options={'verbose_name': 'Cliente restringido', 'verbose_name_plural': 'Clientes restringidos'},
        ),
    ]
