# Generated by Django 4.2.5 on 2023-10-11 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_categoria_remove_permanente_acceso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='restringido',
        ),
        migrations.RemoveField(
            model_name='restringidos',
            name='agregado_por',
        ),
        migrations.RemoveField(
            model_name='restringidos',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='restringidos',
            name='tipo_empresa',
        ),
    ]
