# Generated by Django 4.2.5 on 2023-10-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_categoria_fecha_registro_empresas_fecha_registro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permanente',
            old_name='categoria1',
            new_name='categoria',
        ),
    ]
