# Generated by Django 4.2.5 on 2023-10-12 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0004_cliente_fecha_registro_contacto_fecha_registro_and_more'),
        ('acl', '0006_alter_permanente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.cliente'),
        ),
    ]
