# Generated by Django 4.2.5 on 2023-10-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientdata', '0004_cliente_fecha_registro_contacto_fecha_registro_and_more'),
        ('acl', '0007_alter_temporal_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporal',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='restringidos',
            name='nombre_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientdata.cliente'),
        ),
        migrations.DeleteModel(
            name='Empresas',
        ),
        migrations.DeleteModel(
            name='temporal',
        ),
    ]
